name: 'Check semantic version increased'
description:
  'Compares the current version number with the previous version number to
  ensure either the major, minor or patch version has increased.'
author: Aleo Yakas

inputs:
  current-version:
    description: 'The current version of the product. e.g. 3.2.1'
    required: true

  previous-version:
    description: 'The previous version of the product. e.g. 3.2.0'
    required: true

  allow-pre-release:
    description:
      'Determines if the `current-version` can be a pre-release version.'
    default: 'False'

outputs:
  is-version-increased:
    description:
      '`True` if the current version is greater than the previous version;
      `False` if the current version is less than or equal to the previous
      version.'

runs:
  using: node20
  main: dist/index.js

branding:
  color: blue
  icon: git-branch
